# Generated by Django 3.2.8 on 2021-10-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Facial and Skin Treatments'), (2, 'Massage'), (3, 'Lazer Treatments'), (4, 'Hand and Foot Treatments'), (5, 'Hair Services')], default=2)),
                ('description', models.TextField(max_length=800)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
