# Generated by Django 3.2.8 on 2021-10-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='name',
            field=models.CharField(default='to be advised', max_length=100),
            preserve_default=False,
        ),
    ]
