# Generated by Django 3.2.8 on 2021-10-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_treatment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='image',
            field=models.CharField(default='to be conf', max_length=300),
            preserve_default=False,
        ),
    ]
