# Generated by Django 3.2.8 on 2021-10-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_treatment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
