# Generated by Django 3.2.8 on 2021-10-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20211027_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone_number', models.IntegerField(max_length=13)),
                ('email_address', models.EmailField(max_length=254)),
                ('payment_method', models.IntegerField(choices=[(1, 'VISA'), (2, 'MASTER CARD'), (3, 'CRYPTO'), (4, 'CASH')], default=0)),
            ],
        ),
    ]
