# Generated by Django 3.2.8 on 2021-10-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_treatment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='category',
            field=models.CharField(choices=[(1, 'Facial and Skin Treatments'), (2, 'Massage'), (3, 'Lazer Treatments'), (4, 'Hand and Foot Treatments'), (5, 'Hair Services')], default=1, max_length=1),
        ),
    ]
