# Generated by Django 3.2.8 on 2021-10-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_client'),
        ('main_app', '0009_alter_treatment_category'),
    ]

    operations = [
    ]
