# Generated by Django 3.2.8 on 2021-10-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_0007_client_0009_alter_treatment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
