# Generated by Django 3.2.8 on 2021-10-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20211028_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
