# Generated by Django 3.2.8 on 2021-11-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20211030_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client',
        ),
        migrations.AlterField(
            model_name='booking',
            name='specialist',
            field=models.CharField(choices=[('Skin Care Specialist', (('sk1', 'James'), ('sk2', 'Mary'))), ('Registered Massage Therapist', (('rmt1', 'Robert'), ('rmt1', 'Patricia'))), ('Laser Technitian', (('lsr1', 'Jennifer'), ('lsr2', 'Michael'))), ('Non-Registered Massage provider', (('Non-RMT1', 'Pam Beesly'), ('Non-RMT2', 'Jim Halpert'))), ('Hair Styles', (('HS-1', 'Angela Martin'), ('HS-2', 'Andy Bernard'))), ('any', 'any')], max_length=50),
        ),
    ]
