# Generated by Django 3.2.8 on 2021-11-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_booking_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
